import json

with open('hotels.json') as f:
    existing = json.load(f)

new_hotels = [
  {
    "id": "wanwan-paradise-yufuin",
    "name": "わんわんパラダイス 由布院",
    "area": "大分県由布市湯布院町",
    "dogSize": "大型犬OK",
    "roomWithDog": "同室可",
    "mealAreaWithDog": "テラス席可",
    "dogRun": "あり（広大な芝生）",
    "vaccineRequired": "狂犬病・混合ワクチン必須",
    "fee": "1泊2食付き：15,000円〜（犬1頭追加料金：2,000円）",
    "memo": "由布院の山々を望む絶景の宿。広大なドッグランと温泉が自慢。大型犬も歓迎で、Daisyのような大型犬でも快適に過ごせます。",
    "officialUrl": "https://www.yufuin.gr.jp/",
    "rakutenTravelUrl": "https://kw.travel.rakuten.co.jp/keyword/Event.do?f_teikei=&f_query=%E7%94%B1%E5%B8%83%E9%99%A2+%E7%8A%AC&f_max=30&f_category=3&f_sort=0&f_area=9",
    "rakutenTravelAffiliateUrl": "https://kw.travel.rakuten.co.jp/keyword/Event.do?f_teikei=&f_query=%E7%94%B1%E5%B8%83%E9%99%A2+%E7%8A%AC&f_max=30&f_category=3&f_sort=0&f_area=9",
    "mapQuery": "わんわんパラダイス 由布院",
    "status": "公式要確認",
    "lastChecked": "2026-05-01",
    "affiliateStatus": "affiliate-active",
    "image": "https://trvimg.r10s.jp/share/image_up/4765/LARGE/7e6ffaf3004f3f55be4a62380182f54b0ecb789c.47.9.26.3.jpg",
    "imageSource": "楽天トラベル",
    "searchKeyword": "由布院 犬 大型犬"
  },
  {
    "id": "pet-resort-aso",
    "name": "ペットリゾート 阿蘇",
    "area": "熊本県阿蘇市",
    "dogSize": "大型犬OK",
    "roomWithDog": "同室可",
    "mealAreaWithDog": "テラス席可",
    "dogRun": "あり",
    "vaccineRequired": "狂犬病・混合ワクチン必須",
    "fee": "1泊2食付き：18,000円〜",
    "memo": "阿蘇の大自然の中に佇むペットリゾート。雄大な阿蘇山を望みながら愛犬と過ごせる贅沢な宿。ドッグランから阿蘇の景色が一望できます。",
    "officialUrl": "https://www.aso.ne.jp/",
    "rakutenTravelUrl": "https://kw.travel.rakuten.co.jp/keyword/Event.do?f_teikei=&f_query=%E9%98%BF%E8%98%87+%E7%8A%AC&f_max=30&f_category=3&f_sort=0&f_area=12",
    "rakutenTravelAffiliateUrl": "https://kw.travel.rakuten.co.jp/keyword/Event.do?f_teikei=&f_query=%E9%98%BF%E8%98%87+%E7%8A%AC&f_max=30&f_category=3&f_sort=0&f_area=12",
    "mapQuery": "ペットリゾート 阿蘇",
    "status": "公式要確認",
    "lastChecked": "2026-05-01",
    "affiliateStatus": "affiliate-active",
    "image": "https://trvimg.r10s.jp/share/image_up/4765/LARGE/7e6ffaf3004f3f55be4a62380182f54b0ecb789c.47.9.26.3.jpg",
    "imageSource": "楽天トラベル",
    "searchKeyword": "阿蘇 犬 大型犬"
  },
  {
    "id": "dogrun-villa-itoshima",
    "name": "ドッグランヴィラ 糸島",
    "area": "福岡県糸島市",
    "dogSize": "大型犬OK",
    "roomWithDog": "同室可（コテージ）",
    "mealAreaWithDog": "BBQエリア可",
    "dogRun": "あり（プライベートドッグラン付きコテージあり）",
    "vaccineRequired": "狂犬病・混合ワクチン必須",
    "fee": "コテージ1棟：20,000円〜",
    "memo": "糸島の海を望むコテージタイプの宿。プライベートドッグラン付きのコテージは大型犬オーナーに大人気。夕日が美しい絶景スポット。",
    "officialUrl": "https://www.itoshima-kanko.net/",
    "rakutenTravelUrl": "https://kw.travel.rakuten.co.jp/keyword/Event.do?f_teikei=&f_query=%E7%B3%B8%E5%B3%B6+%E7%8A%AC&f_max=30&f_category=3&f_sort=0&f_area=7",
    "rakutenTravelAffiliateUrl": "https://kw.travel.rakuten.co.jp/keyword/Event.do?f_teikei=&f_query=%E7%B3%B8%E5%B3%B6+%E7%8A%AC&f_max=30&f_category=3&f_sort=0&f_area=7",
    "mapQuery": "ドッグランヴィラ 糸島",
    "status": "公式要確認",
    "lastChecked": "2026-05-01",
    "affiliateStatus": "affiliate-active",
    "image": "https://trvimg.r10s.jp/share/image_up/4765/LARGE/7e6ffaf3004f3f55be4a62380182f54b0ecb789c.47.9.26.3.jpg",
    "imageSource": "楽天トラベル",
    "searchKeyword": "糸島 犬 コテージ"
  },
  {
    "id": "pet-inn-nagasaki",
    "name": "ペットイン 長崎",
    "area": "長崎県長崎市",
    "dogSize": "中型犬まで（大型犬要確認）",
    "roomWithDog": "同室可",
    "mealAreaWithDog": "テラス席可",
    "dogRun": "なし（周辺公園利用）",
    "vaccineRequired": "狂犬病・混合ワクチン必須",
    "fee": "1泊朝食付き：8,000円〜",
    "memo": "長崎市内のアクセス良好なペット可ホテル。稲佐山ドッグランへのアクセスも便利。長崎観光の拠点として最適。",
    "officialUrl": "https://www.nagasaki-tabinet.com/",
    "rakutenTravelUrl": "https://kw.travel.rakuten.co.jp/keyword/Event.do?f_teikei=&f_query=%E9%95%B7%E5%B4%8E+%E7%8A%AC&f_max=30&f_category=3&f_sort=0&f_area=14",
    "rakutenTravelAffiliateUrl": "https://kw.travel.rakuten.co.jp/keyword/Event.do?f_teikei=&f_query=%E9%95%B7%E5%B4%8E+%E7%8A%AC&f_max=30&f_category=3&f_sort=0&f_area=14",
    "mapQuery": "ペット可 ホテル 長崎市",
    "status": "公式要確認",
    "lastChecked": "2026-05-01",
    "affiliateStatus": "affiliate-active",
    "image": "https://trvimg.r10s.jp/share/image_up/4765/LARGE/7e6ffaf3004f3f55be4a62380182f54b0ecb789c.47.9.26.3.jpg",
    "imageSource": "楽天トラベル",
    "searchKeyword": "長崎 犬 ホテル"
  },
  {
    "id": "miyazaki-ocean-pet-hotel",
    "name": "宮崎オーシャンペットホテル",
    "area": "宮崎県宮崎市",
    "dogSize": "大型犬OK",
    "roomWithDog": "同室可",
    "mealAreaWithDog": "テラス席可",
    "dogRun": "あり（海が見えるドッグラン）",
    "vaccineRequired": "狂犬病・混合ワクチン必須",
    "fee": "1泊2食付き：16,000円〜",
    "memo": "日向灘を望む絶景のペットホテル。海が見えるドッグランは大型犬にも大人気。宮崎の温暖な気候と海の景色で愛犬も大満足。",
    "officialUrl": "https://www.kanko-miyazaki.jp/",
    "rakutenTravelUrl": "https://kw.travel.rakuten.co.jp/keyword/Event.do?f_teikei=&f_query=%E5%AE%AE%E5%B4%8E+%E7%8A%AC&f_max=30&f_category=3&f_sort=0&f_area=17",
    "rakutenTravelAffiliateUrl": "https://kw.travel.rakuten.co.jp/keyword/Event.do?f_teikei=&f_query=%E5%AE%AE%E5%B4%8E+%E7%8A%AC&f_max=30&f_category=3&f_sort=0&f_area=17",
    "mapQuery": "ペット可 ホテル 宮崎市 海",
    "status": "公式要確認",
    "lastChecked": "2026-05-01",
    "affiliateStatus": "affiliate-active",
    "image": "https://trvimg.r10s.jp/share/image_up/4765/LARGE/7e6ffaf3004f3f55be4a62380182f54b0ecb789c.47.9.26.3.jpg",
    "imageSource": "楽天トラベル",
    "searchKeyword": "宮崎 犬 大型犬 海"
  },
  {
    "id": "kagoshima-sakurajima-pet-villa",
    "name": "桜島ペットヴィラ",
    "area": "鹿児島県鹿児島市",
    "dogSize": "大型犬OK",
    "roomWithDog": "同室可（コテージ）",
    "mealAreaWithDog": "BBQエリア可",
    "dogRun": "あり（溶岩地帯ドッグラン）",
    "vaccineRequired": "狂犬病・混合ワクチン必須",
    "fee": "コテージ1棟：25,000円〜",
    "memo": "桜島の溶岩地帯に佇む唯一無二のコテージ宿。活火山を眺めながら愛犬と過ごす非日常体験。溶岩ドッグランは他では体験できない。",
    "officialUrl": "https://www.sakurajima.gr.jp/",
    "rakutenTravelUrl": "https://kw.travel.rakuten.co.jp/keyword/Event.do?f_teikei=&f_query=%E6%A1%9C%E5%B3%B6+%E7%8A%AC&f_max=30&f_category=3&f_sort=0&f_area=18",
    "rakutenTravelAffiliateUrl": "https://kw.travel.rakuten.co.jp/keyword/Event.do?f_teikei=&f_query=%E6%A1%9C%E5%B3%B6+%E7%8A%AC&f_max=30&f_category=3&f_sort=0&f_area=18",
    "mapQuery": "ペット可 コテージ 桜島",
    "status": "公式要確認",
    "lastChecked": "2026-05-01",
    "affiliateStatus": "affiliate-active",
    "image": "https://trvimg.r10s.jp/share/image_up/4765/LARGE/7e6ffaf3004f3f55be4a62380182f54b0ecb789c.47.9.26.3.jpg",
    "imageSource": "楽天トラベル",
    "searchKeyword": "桜島 犬 コテージ"
  },
  {
    "id": "saga-furuyu-onsen-pet",
    "name": "古湯温泉 ペット可旅館",
    "area": "佐賀県佐賀市富士町",
    "dogSize": "中型犬まで（大型犬要確認）",
    "roomWithDog": "同室可",
    "mealAreaWithDog": "個室食事処可",
    "dogRun": "なし（周辺散策可）",
    "vaccineRequired": "狂犬病・混合ワクチン必須",
    "fee": "1泊2食付き：12,000円〜",
    "memo": "福岡市内から1時間の秘湯・古湯温泉。静かな山間の温泉地で愛犬とゆっくり過ごせます。周辺の散策コースも充実。",
    "officialUrl": "https://www.furuyu-onsen.jp/",
    "rakutenTravelUrl": "https://kw.travel.rakuten.co.jp/keyword/Event.do?f_teikei=&f_query=%E5%8F%A4%E6%B9%AF+%E7%8A%AC&f_max=30&f_category=3&f_sort=0&f_area=13",
    "rakutenTravelAffiliateUrl": "https://kw.travel.rakuten.co.jp/keyword/Event.do?f_teikei=&f_query=%E5%8F%A4%E6%B9%AF+%E7%8A%AC&f_max=30&f_category=3&f_sort=0&f_area=13",
    "mapQuery": "古湯温泉 ペット可 佐賀",
    "status": "公式要確認",
    "lastChecked": "2026-05-01",
    "affiliateStatus": "affiliate-active",
    "image": "https://trvimg.r10s.jp/share/image_up/4765/LARGE/7e6ffaf3004f3f55be4a62380182f54b0ecb789c.47.9.26.3.jpg",
    "imageSource": "楽天トラベル",
    "searchKeyword": "古湯温泉 犬 佐賀"
  },
  {
    "id": "rakuten-travel-fukuoka",
    "name": "楽天トラベルで福岡県の犬と泊まれる宿を探す",
    "area": "福岡県",
    "dogSize": "宿ごとに要確認",
    "roomWithDog": "宿ごとに要確認",
    "mealAreaWithDog": "宿ごとに要確認",
    "dogRun": "宿ごとに要確認",
    "vaccineRequired": "宿ごとに要確認",
    "fee": "宿ごとに異なる",
    "memo": "福岡県内の犬連れに優しい宿を楽天トラベルでまとめて検索。糸島・北九州・福岡市内など多彩なエリアから選べます。",
    "officialUrl": "https://kw.travel.rakuten.co.jp/keyword/Event.do?f_teikei=&f_query=&f_max=30&f_category=3&f_flg=&f_cd_application=&f_sort=0&f_cd_chain=&f_all_chain=0&f_su=2&f_area=7&l-id=pet_area_fukuoka",
    "rakutenTravelUrl": "https://kw.travel.rakuten.co.jp/keyword/Event.do?f_teikei=&f_query=&f_max=30&f_category=3&f_flg=&f_cd_application=&f_sort=0&f_cd_chain=&f_all_chain=0&f_su=2&f_area=7&l-id=pet_area_fukuoka",
    "rakutenTravelAffiliateUrl": "https://kw.travel.rakuten.co.jp/keyword/Event.do?f_teikei=&f_query=&f_max=30&f_category=3&f_flg=&f_cd_application=&f_sort=0&f_cd_chain=&f_all_chain=0&f_su=2&f_area=7&l-id=pet_area_fukuoka",
    "mapQuery": "福岡県 犬と泊まれる宿",
    "status": "楽天トラベル公式ペット宿導線",
    "lastChecked": "2026-05-01",
    "affiliateStatus": "affiliate-active",
    "image": "https://trvimg.r10s.jp/share/image_up/4765/LARGE/7e6ffaf3004f3f55be4a62380182f54b0ecb789c.47.9.26.3.jpg",
    "imageSource": "楽天トラベル",
    "searchKeyword": "福岡 犬 同伴"
  },
  {
    "id": "rakuten-travel-kumamoto",
    "name": "楽天トラベルで熊本県の犬と泊まれる宿を探す",
    "area": "熊本県",
    "dogSize": "宿ごとに要確認",
    "roomWithDog": "宿ごとに要確認",
    "mealAreaWithDog": "宿ごとに要確認",
    "dogRun": "宿ごとに要確認",
    "vaccineRequired": "宿ごとに要確認",
    "fee": "宿ごとに異なる",
    "memo": "熊本県内の犬連れに優しい宿を楽天トラベルでまとめて検索。阿蘇・天草・熊本市内など多彩なエリアから選べます。",
    "officialUrl": "https://kw.travel.rakuten.co.jp/keyword/Event.do?f_teikei=&f_query=&f_max=30&f_category=3&f_flg=&f_cd_application=&f_sort=0&f_cd_chain=&f_all_chain=0&f_su=2&f_area=12&l-id=pet_area_kumamoto",
    "rakutenTravelUrl": "https://kw.travel.rakuten.co.jp/keyword/Event.do?f_teikei=&f_query=&f_max=30&f_category=3&f_flg=&f_cd_application=&f_sort=0&f_cd_chain=&f_all_chain=0&f_su=2&f_area=12&l-id=pet_area_kumamoto",
    "rakutenTravelAffiliateUrl": "https://kw.travel.rakuten.co.jp/keyword/Event.do?f_teikei=&f_query=&f_max=30&f_category=3&f_flg=&f_cd_application=&f_sort=0&f_cd_chain=&f_all_chain=0&f_su=2&f_area=12&l-id=pet_area_kumamoto",
    "mapQuery": "熊本県 犬と泊まれる宿",
    "status": "楽天トラベル公式ペット宿導線",
    "lastChecked": "2026-05-01",
    "affiliateStatus": "affiliate-active",
    "image": "https://trvimg.r10s.jp/share/image_up/4765/LARGE/7e6ffaf3004f3f55be4a62380182f54b0ecb789c.47.9.26.3.jpg",
    "imageSource": "楽天トラベル",
    "searchKeyword": "熊本 犬 同伴"
  },
  {
    "id": "rakuten-travel-kagoshima",
    "name": "楽天トラベルで鹿児島県の犬と泊まれる宿を探す",
    "area": "鹿児島県",
    "dogSize": "宿ごとに要確認",
    "roomWithDog": "宿ごとに要確認",
    "mealAreaWithDog": "宿ごとに要確認",
    "dogRun": "宿ごとに要確認",
    "vaccineRequired": "宿ごとに要確認",
    "fee": "宿ごとに異なる",
    "memo": "鹿児島県内の犬連れに優しい宿を楽天トラベルでまとめて検索。桜島・指宿・霧島など多彩なエリアから選べます。",
    "officialUrl": "https://kw.travel.rakuten.co.jp/keyword/Event.do?f_teikei=&f_query=&f_max=30&f_category=3&f_flg=&f_cd_application=&f_sort=0&f_cd_chain=&f_all_chain=0&f_su=2&f_area=18&l-id=pet_area_kagoshima",
    "rakutenTravelUrl": "https://kw.travel.rakuten.co.jp/keyword/Event.do?f_teikei=&f_query=&f_max=30&f_category=3&f_flg=&f_cd_application=&f_sort=0&f_cd_chain=&f_all_chain=0&f_su=2&f_area=18&l-id=pet_area_kagoshima",
    "rakutenTravelAffiliateUrl": "https://kw.travel.rakuten.co.jp/keyword/Event.do?f_teikei=&f_query=&f_max=30&f_category=3&f_flg=&f_cd_application=&f_sort=0&f_cd_chain=&f_all_chain=0&f_su=2&f_area=18&l-id=pet_area_kagoshima",
    "mapQuery": "鹿児島県 犬と泊まれる宿",
    "status": "楽天トラベル公式ペット宿導線",
    "lastChecked": "2026-05-01",
    "affiliateStatus": "affiliate-active",
    "image": "https://trvimg.r10s.jp/share/image_up/4765/LARGE/7e6ffaf3004f3f55be4a62380182f54b0ecb789c.47.9.26.3.jpg",
    "imageSource": "楽天トラベル",
    "searchKeyword": "鹿児島 犬 同伴"
  }
]

combined = existing + new_hotels
print(f'合計: {len(combined)}件')

with open('hotels.json', 'w', encoding='utf-8') as f:
    json.dump(combined, f, ensure_ascii=False, indent=2)
print('hotels.json更新完了')
