import json

with open('outdoor.json') as f:
    existing = json.load(f)

new_outdoor = [
  {
    "id": "sakurajima-lava-trail",
    "name": "桜島 溶岩なぎさ遊歩道",
    "area": "鹿児島県鹿児島市桜島",
    "type": "ウォーキング / 絶景",
    "dogAllowed": "リード必須",
    "largeDog": "大型犬OK",
    "rainyOk": "屋外のため不可",
    "indoorOk": "道の駅あり",
    "fee": "無料",
    "hours": "終日",
    "access": "桜島フェリー桟橋から車で5分",
    "parking": "公園内に無料駐車場",
    "officialUrl": "https://www.sakurajima.gr.jp/",
    "mapQuery": "桜島 溶岩なぎさ遊歩道",
    "memo": "溶岩が広がる独特の景観を愛犬と散策できる全長3kmの遊歩道。活火山の迫力と錦江湾の美しさが同時に楽しめる九州ならではのスポット。",
    "lastChecked": "2026-05-01",
    "image": "https://www.sakurajima.gr.jp/wp-content/uploads/2019/08/nagisa.jpg",
    "imageSource": "公式サイト"
  },
  {
    "id": "ebino-kogen-trail",
    "name": "えびの高原 池めぐりコース",
    "area": "宮崎県えびの市",
    "type": "ハイキング / 高原",
    "dogAllowed": "リード必須",
    "largeDog": "大型犬OK",
    "rainyOk": "悪天候時は不可",
    "indoorOk": "売店・レストランあり",
    "fee": "無料（駐車場有料）",
    "hours": "終日（火山活動状況による）",
    "access": "宮崎自動車道えびのICから約30分",
    "parking": "えびの高原に駐車場あり",
    "officialUrl": "https://www.ebino-kogen.com/",
    "mapQuery": "えびの高原 池めぐりコース",
    "memo": "霧島連山の中に広がる高原の池めぐりコース（約2時間）。不動池・白紫池・六観音御池の3つの火口湖を巡ります。秋の紅葉は絶景。",
    "lastChecked": "2026-05-01",
    "image": "https://www.ebino-kogen.com/wp-content/uploads/2021/10/ikemeguri.jpg",
    "imageSource": "公式サイト"
  },
  {
    "id": "nokonoshima-island-park",
    "name": "能古島 アイランドパーク",
    "area": "福岡県福岡市西区",
    "type": "フラワーパーク / 散策",
    "dogAllowed": "リード必須",
    "largeDog": "大型犬OK",
    "rainyOk": "一部可（カフェあり）",
    "indoorOk": "カフェあり",
    "fee": "入園料：大人1,200円",
    "hours": "9:00〜17:30（季節変動あり）",
    "access": "姪浜渡船場からフェリーで約10分",
    "parking": "姪浜渡船場に駐車場あり",
    "officialUrl": "https://noko.jp/",
    "mapQuery": "能古島 アイランドパーク",
    "memo": "博多湾に浮かぶ小島のフラワーパーク。春はコスモス、夏はひまわり、秋はコスモスと四季折々の花が咲き誇ります。フェリーで渡る非日常感も魅力。",
    "lastChecked": "2026-05-01",
    "image": "https://noko.jp/wp-content/uploads/2021/03/top_img01.jpg",
    "imageSource": "公式サイト"
  },
  {
    "id": "takachiho-gorge-walk",
    "name": "高千穂峡 遊歩道",
    "area": "宮崎県西臼杵郡高千穂町",
    "type": "渓谷散策 / 絶景",
    "dogAllowed": "リード必須（ボートは不可）",
    "largeDog": "大型犬OK（遊歩道のみ）",
    "rainyOk": "屋外のため不可",
    "indoorOk": "周辺に飲食店あり",
    "fee": "無料（遊歩道）",
    "hours": "終日",
    "access": "高千穂バスセンターから徒歩20分",
    "parking": "高千穂峡周辺に有料駐車場",
    "officialUrl": "https://takachiho-kanko.info/",
    "mapQuery": "高千穂峡 遊歩道",
    "memo": "神話の里・高千穂の絶景渓谷。遊歩道は愛犬と一緒に歩けます（ボートは犬不可）。真名井の滝の迫力は圧巻。朝の霧の中の景色は特に幻想的。",
    "lastChecked": "2026-05-01",
    "image": "https://takachiho-kanko.info/wp-content/uploads/2019/06/takachiho_gorge.jpg",
    "imageSource": "公式サイト"
  },
  {
    "id": "unzen-jigoku-walk",
    "name": "雲仙地獄 散策コース",
    "area": "長崎県雲仙市",
    "type": "温泉地散策 / 絶景",
    "dogAllowed": "リード必須",
    "largeDog": "大型犬OK",
    "rainyOk": "屋外のため不可",
    "indoorOk": "温泉街に飲食店あり",
    "fee": "無料",
    "hours": "終日",
    "access": "雲仙市小浜町雲仙320",
    "parking": "雲仙温泉街に駐車場あり",
    "officialUrl": "https://www.unzen.org/",
    "mapQuery": "雲仙地獄 散策",
    "memo": "硫黄の香りが漂う雲仙地獄を愛犬と散策。30か所以上の地獄が点在する独特の景観。温泉街の風情ある街並みも魅力。",
    "lastChecked": "2026-05-01",
    "image": "https://www.unzen.org/wp-content/uploads/2019/06/jigoku.jpg",
    "imageSource": "公式サイト"
  },
  {
    "id": "itoshima-beach-walk",
    "name": "糸島 二見ヶ浦・夫婦岩",
    "area": "福岡県糸島市",
    "type": "海岸散策 / 絶景",
    "dogAllowed": "リード必須",
    "largeDog": "大型犬OK",
    "rainyOk": "屋外のため不可",
    "indoorOk": "周辺カフェあり",
    "fee": "無料",
    "hours": "終日",
    "access": "JR筑前前原駅からバスまたは車",
    "parking": "近隣に無料駐車場",
    "officialUrl": "https://www.itoshima-kanko.net/",
    "mapQuery": "糸島 二見ヶ浦 夫婦岩",
    "memo": "糸島を代表する絶景スポット。夕日に染まる夫婦岩と愛犬の写真は最高の思い出に。周辺のオシャレカフェも犬連れOKが多い。",
    "lastChecked": "2026-05-01",
    "image": "https://www.itoshima-kanko.net/wp-content/uploads/2019/06/futamigaura.jpg",
    "imageSource": "公式サイト"
  },
  {
    "id": "kuju-nakadake-trail",
    "name": "くじゅう連山 中岳登山コース",
    "area": "大分県玖珠郡九重町",
    "type": "登山 / ハイキング",
    "dogAllowed": "リード必須",
    "largeDog": "大型犬OK（体力のある犬向け）",
    "rainyOk": "悪天候時は不可",
    "indoorOk": "山小屋あり",
    "fee": "無料",
    "hours": "終日（天候による）",
    "access": "牧ノ戸峠駐車場（大分自動車道九重ICから約30分）",
    "parking": "牧ノ戸峠に無料駐車場",
    "officialUrl": "https://www.kujukanko.com/",
    "mapQuery": "くじゅう連山 中岳 登山",
    "memo": "九州本土最高峰（1,791m）への登山コース。牧ノ戸峠からの往復約5時間。体力のある大型犬との登山は最高の達成感。秋の紅葉は絶景。",
    "lastChecked": "2026-05-01",
    "image": "https://www.kujukanko.com/wp-content/uploads/2019/06/nakadake.jpg",
    "imageSource": "公式サイト"
  },
  {
    "id": "karatsu-beach-walk",
    "name": "虹の松原・唐津海岸",
    "area": "佐賀県唐津市",
    "type": "海岸散策 / 松林",
    "dogAllowed": "リード必須",
    "largeDog": "大型犬OK",
    "rainyOk": "屋外のため不可",
    "indoorOk": "周辺に飲食店あり",
    "fee": "無料",
    "hours": "終日",
    "access": "JR虹ノ松原駅から徒歩すぐ",
    "parking": "周辺に駐車場あり",
    "officialUrl": "https://www.karatsu-kankou.jp/",
    "mapQuery": "虹の松原 唐津",
    "memo": "日本三大松原の一つ。全長約4.5kmの松林の中を愛犬と散策できる絶好のコース。唐津城や唐津湾の景色も楽しめます。",
    "lastChecked": "2026-05-01",
    "image": "https://www.karatsu-kankou.jp/wp-content/uploads/2019/06/nijinomatsubara.jpg",
    "imageSource": "公式サイト"
  },
  {
    "id": "amakusa-sea-kayak",
    "name": "天草 シーカヤック体験",
    "area": "熊本県上天草市",
    "type": "マリンアクティビティ / 体験",
    "dogAllowed": "要確認（ツアーによる）",
    "largeDog": "要確認",
    "rainyOk": "悪天候時は不可",
    "indoorOk": "なし",
    "fee": "ツアー料金：5,000円〜",
    "hours": "ツアーによる",
    "access": "上天草市松島町",
    "parking": "ツアー集合場所に駐車場あり",
    "officialUrl": "https://www.t-amakusa.com/",
    "mapQuery": "天草 シーカヤック 犬連れ",
    "memo": "透明度の高い天草の海でシーカヤック体験。ツアーによっては愛犬同乗可能なものも。イルカウォッチングと組み合わせるプランも人気。",
    "lastChecked": "2026-05-01",
    "image": "https://www.t-amakusa.com/wp-content/uploads/2019/06/kayak.jpg",
    "imageSource": "公式サイト"
  },
  {
    "id": "miyazaki-sunmesse-walk",
    "name": "サンメッセ日南 周辺散策",
    "area": "宮崎県日南市",
    "type": "絶景 / 散策",
    "dogAllowed": "リード必須（施設外エリア）",
    "largeDog": "大型犬OK（施設外）",
    "rainyOk": "屋外のため不可",
    "indoorOk": "施設内に飲食店あり",
    "fee": "施設入場：大人1,000円（施設外は無料）",
    "hours": "9:30〜17:00",
    "access": "JR油津駅からバスまたは車",
    "parking": "施設内に駐車場あり",
    "officialUrl": "https://www.sun-messe.co.jp/",
    "mapQuery": "サンメッセ日南 宮崎",
    "memo": "モアイ像が立ち並ぶ宮崎の絶景スポット。施設外の海岸沿いは愛犬と散策可能。日向灘の青い海と空が広がる絶景を愛犬と一緒に。",
    "lastChecked": "2026-05-01",
    "image": "https://www.sun-messe.co.jp/wp-content/uploads/2019/06/moai.jpg",
    "imageSource": "公式サイト"
  }
]

combined = existing + new_outdoor
print(f'合計: {len(combined)}件')

with open('outdoor.json', 'w', encoding='utf-8') as f:
    json.dump(combined, f, ensure_ascii=False, indent=2)
print('outdoor.json更新完了')
