import json

with open('spots.json') as f:
    existing = json.load(f)

new_spots = [
  {
    "id": "marinoa-city-dogrun-fukuoka",
    "name": "マリノアシティ福岡 ドッグラン",
    "area": "福岡県福岡市西区",
    "type": "dogrun",
    "large_dog": "大型犬OK",
    "largeDog": "大型犬OK",
    "fee": "無料（施設利用者）",
    "hours": "10:00〜20:00",
    "access": "福岡市西区小戸2丁目 / 地下鉄姪浜駅からバス",
    "parking": "あり（有料）",
    "rainyOk": "屋外のため不可",
    "indoorOk": "ショッピングモール内施設あり",
    "dogAllowed": "リード必須",
    "officialUrl": "https://www.marinoacity.com/",
    "mapQuery": "マリノアシティ福岡 ドッグラン",
    "memo": "アウトレットモール隣接のドッグラン。買い物ついでに愛犬を遊ばせられる便利なスポット。大型犬も走り回れる広さがあります。",
    "status": "公式要確認",
    "lastChecked": "2026-05-01",
    "weekendRecommended": True,
    "vaccineRequired": "要確認"
  },
  {
    "id": "nokonoshima-walk-fukuoka",
    "name": "能古島 アイランドパーク",
    "area": "福岡県福岡市西区",
    "type": "walk",
    "large_dog": "大型犬OK・リード必須",
    "largeDog": "大型犬OK",
    "fee": "入園料：大人1,200円",
    "hours": "9:00〜17:30（季節変動あり）",
    "access": "姪浜渡船場からフェリーで約10分",
    "parking": "姪浜渡船場に駐車場あり",
    "rainyOk": "一部可",
    "indoorOk": "カフェあり",
    "dogAllowed": "リード必須",
    "officialUrl": "https://noko.jp/",
    "mapQuery": "能古島アイランドパーク 福岡",
    "memo": "博多湾に浮かぶ小島のフラワーパーク。季節の花々と海の景色が美しく、愛犬との散歩に最適。フェリーで渡る非日常感も魅力。",
    "status": "公式要確認",
    "lastChecked": "2026-05-01",
    "weekendRecommended": True
  },
  {
    "id": "uminonakamichi-park-walk-fukuoka",
    "name": "海の中道海浜公園 散策エリア",
    "area": "福岡市東区",
    "type": "walk",
    "large_dog": "大型犬OK・リード必須",
    "largeDog": "大型犬OK",
    "fee": "入園料：大人450円",
    "hours": "9:30〜17:30（季節変動あり）",
    "access": "JR海ノ中道駅から徒歩すぐ",
    "parking": "あり（有料）",
    "rainyOk": "屋外のため不可",
    "indoorOk": "一部施設あり",
    "dogAllowed": "リード必須・一部エリア立入禁止",
    "officialUrl": "https://uminaka.jp/",
    "mapQuery": "海の中道海浜公園 福岡",
    "memo": "広大な国営公園。ドッグランだけでなく、芝生広場や海辺の散策も楽しめます。季節の花も見事で、Daisyも大喜びのスポット。",
    "status": "公式要確認",
    "lastChecked": "2026-05-01",
    "weekendRecommended": True
  },
  {
    "id": "maizuru-park-walk-fukuoka",
    "name": "舞鶴公園（福岡城跡）",
    "area": "福岡県福岡市中央区",
    "type": "walk",
    "large_dog": "大型犬OK・リード必須",
    "largeDog": "大型犬OK",
    "fee": "無料",
    "hours": "終日開放",
    "access": "地下鉄大濠公園駅から徒歩5分",
    "parking": "周辺に有料駐車場",
    "rainyOk": "屋外のため不可",
    "indoorOk": "なし",
    "dogAllowed": "リード必須",
    "officialUrl": "https://www.midorimachi.jp/park/maizuru/",
    "mapQuery": "舞鶴公園 福岡市",
    "memo": "福岡城跡を中心とした歴史ある公園。桜の名所としても有名で、大濠公園と合わせて散歩するコースが人気。",
    "status": "公式要確認",
    "lastChecked": "2026-05-01",
    "weekendRecommended": True
  },
  {
    "id": "itoshima-beach-walk",
    "name": "糸島 二見ヶ浦・夫婦岩",
    "area": "糸島市",
    "type": "walk",
    "large_dog": "大型犬OK・リード必須",
    "largeDog": "大型犬OK",
    "fee": "無料",
    "hours": "終日",
    "access": "JR筑前前原駅からバスまたは車",
    "parking": "近隣に無料駐車場",
    "rainyOk": "屋外のため不可",
    "indoorOk": "周辺カフェあり",
    "dogAllowed": "リード必須",
    "officialUrl": "https://www.itoshima-kanko.net/",
    "mapQuery": "糸島 二見ヶ浦 夫婦岩",
    "memo": "糸島を代表する絶景スポット。夕日に染まる夫婦岩と愛犬の写真は最高の思い出に。周辺のオシャレカフェも犬連れOKが多い。",
    "status": "公式要確認",
    "lastChecked": "2026-05-01",
    "weekendRecommended": True
  },
  {
    "id": "kawachi-wisteria-walk-kitakyushu",
    "name": "河内藤園（北九州）",
    "area": "福岡県北九州市八幡東区",
    "type": "walk",
    "large_dog": "大型犬OK・リード必須",
    "largeDog": "大型犬OK",
    "fee": "入園料：500〜1,500円（季節変動）",
    "hours": "8:00〜18:00（開花期のみ）",
    "access": "北九州市八幡東区河内2-2-48",
    "parking": "あり（有料）",
    "rainyOk": "屋外のため不可",
    "indoorOk": "なし",
    "dogAllowed": "リード必須",
    "officialUrl": "https://www.kawachi-fujien.com/",
    "mapQuery": "河内藤園 北九州",
    "memo": "世界的にも有名な藤の名所。4〜5月の開花期は圧巻の美しさ。愛犬と一緒に藤のトンネルを歩く体験は格別です。",
    "status": "公式要確認",
    "lastChecked": "2026-05-01",
    "weekendRecommended": True
  },
  {
    "id": "yufuin-kinrinko-walk",
    "name": "湯布院 金鱗湖 周辺散策",
    "area": "大分県由布市湯布院町",
    "type": "walk",
    "large_dog": "大型犬OK・リード必須",
    "largeDog": "大型犬OK",
    "fee": "無料",
    "hours": "終日",
    "access": "JR由布院駅から徒歩20分",
    "parking": "湯布院町内に有料駐車場",
    "rainyOk": "屋外のため不可",
    "indoorOk": "周辺カフェあり（要確認）",
    "dogAllowed": "リード必須",
    "officialUrl": "https://www.yufuin.gr.jp/",
    "mapQuery": "湯布院 金鱗湖",
    "memo": "湯布院観光の定番スポット。朝霧に包まれた金鱗湖は幻想的な美しさ。湯の坪街道と合わせて愛犬とのんびり散策を楽しめます。",
    "status": "公式要確認",
    "lastChecked": "2026-05-01",
    "weekendRecommended": True
  },
  {
    "id": "beppu-ropeway-dogrun",
    "name": "鶴見岳一気登山道 ペット可散策",
    "area": "大分県別府市",
    "type": "walk",
    "large_dog": "大型犬OK・リード必須",
    "largeDog": "大型犬OK",
    "fee": "無料（登山道）",
    "hours": "終日（天候による）",
    "access": "別府市内から車で約20分",
    "parking": "登山口に駐車場あり",
    "rainyOk": "悪天候時は不可",
    "indoorOk": "なし",
    "dogAllowed": "リード必須",
    "officialUrl": "https://www.beppu-tourism.com/",
    "mapQuery": "鶴見岳 別府 登山",
    "memo": "別府の山を愛犬と一緒に登れるスポット。山頂からの別府湾の眺めは絶景。体力のある大型犬には特におすすめ。",
    "status": "公式要確認",
    "lastChecked": "2026-05-01",
    "weekendRecommended": False
  },
  {
    "id": "aso-nakadake-walk",
    "name": "阿蘇中岳火口周辺 散策",
    "area": "大分県阿蘇市",
    "type": "walk",
    "large_dog": "大型犬OK・リード必須",
    "largeDog": "大型犬OK（火山活動状況による）",
    "fee": "入山料：大人1,000円",
    "hours": "8:00〜18:00（火山活動状況により変動）",
    "access": "阿蘇山上バスターミナルから徒歩",
    "parking": "阿蘇山上に駐車場あり",
    "rainyOk": "悪天候時は不可",
    "indoorOk": "売店あり",
    "dogAllowed": "リード必須・火口周辺は立入禁止区域あり",
    "officialUrl": "https://www.aso.ne.jp/",
    "mapQuery": "阿蘇中岳 火口 散策",
    "memo": "活火山の雄大な景色を愛犬と一緒に楽しめる。草千里ヶ浜との組み合わせで半日コースが人気。火山活動状況の事前確認必須。",
    "status": "公式要確認",
    "lastChecked": "2026-05-01",
    "weekendRecommended": True
  },
  {
    "id": "kuju-mountain-walk",
    "name": "くじゅう連山 牧ノ戸峠ルート",
    "area": "大分県玖珠郡九重町",
    "type": "walk",
    "large_dog": "大型犬OK・リード必須",
    "largeDog": "大型犬OK",
    "fee": "無料",
    "hours": "終日（天候による）",
    "access": "牧ノ戸峠駐車場（大分自動車道九重ICから約30分）",
    "parking": "牧ノ戸峠に無料駐車場",
    "rainyOk": "悪天候時は不可",
    "indoorOk": "売店あり",
    "dogAllowed": "リード必須",
    "officialUrl": "https://www.kujukanko.com/",
    "mapQuery": "くじゅう連山 牧ノ戸峠",
    "memo": "九州最高峰エリアのハイキングコース。標高1,330mの牧ノ戸峠から気軽にスタートできる。秋の紅葉シーズンは特に絶景。",
    "status": "公式要確認",
    "lastChecked": "2026-05-01",
    "weekendRecommended": True
  },
  {
    "id": "nagasaki-glover-walk",
    "name": "グラバー園周辺 散策",
    "area": "長崎県長崎市",
    "type": "walk",
    "large_dog": "大型犬OK・リード必須（一部エリア要確認）",
    "largeDog": "要確認",
    "fee": "グラバー園入園料：大人620円",
    "hours": "8:00〜18:00（季節変動あり）",
    "access": "長崎市南山手町8-1",
    "parking": "周辺に有料駐車場",
    "rainyOk": "屋外のため不可",
    "indoorOk": "周辺カフェあり",
    "dogAllowed": "リード必須・施設内は要確認",
    "officialUrl": "https://www.glover-garden.jp/",
    "mapQuery": "グラバー園 長崎",
    "memo": "長崎の歴史的観光地。グラバー園周辺の坂道散策は愛犬と一緒に楽しめます。長崎港の眺めも絶景。",
    "status": "公式要確認",
    "lastChecked": "2026-05-01",
    "weekendRecommended": True
  },
  {
    "id": "unzen-walk-nagasaki",
    "name": "雲仙温泉 地獄めぐり散策",
    "area": "長崎県雲仙市",
    "type": "walk",
    "large_dog": "大型犬OK・リード必須",
    "largeDog": "大型犬OK",
    "fee": "無料",
    "hours": "終日",
    "access": "雲仙市小浜町雲仙320",
    "parking": "雲仙温泉街に駐車場あり",
    "rainyOk": "屋外のため不可",
    "indoorOk": "温泉街に飲食店あり",
    "dogAllowed": "リード必須",
    "officialUrl": "https://www.unzen.org/",
    "mapQuery": "雲仙温泉 地獄めぐり",
    "memo": "硫黄の香りが漂う雲仙地獄を愛犬と散策。温泉街の風情ある街並みも魅力。愛犬も温泉の湯気を不思議そうに眺めます。",
    "status": "公式要確認",
    "lastChecked": "2026-05-01",
    "weekendRecommended": True
  },
  {
    "id": "saga-yoshinogari-dogrun",
    "name": "吉野ヶ里歴史公園 ドッグラン",
    "area": "佐賀県神埼郡吉野ヶ里町",
    "type": "dogrun",
    "large_dog": "大型犬OK",
    "largeDog": "大型犬OK",
    "fee": "入園料込み：大人460円",
    "hours": "9:00〜17:00（月曜定休）",
    "access": "JR吉野ヶ里公園駅から徒歩15分",
    "parking": "あり（有料）",
    "rainyOk": "屋外のため不可",
    "indoorOk": "一部施設あり",
    "dogAllowed": "リード必須・ドッグランエリアのみノーリード可",
    "officialUrl": "https://www.yoshinogari.jp/",
    "mapQuery": "吉野ヶ里歴史公園 ドッグラン",
    "memo": "弥生時代の遺跡を有する国営公園内のドッグラン。歴史的な雰囲気の中で愛犬を遊ばせられる珍しいスポット。",
    "status": "公式要確認",
    "lastChecked": "2026-05-01",
    "weekendRecommended": True
  },
  {
    "id": "karatsu-beach-walk-saga",
    "name": "虹の松原・唐津海岸",
    "area": "佐賀県唐津市",
    "type": "walk",
    "large_dog": "大型犬OK・リード必須",
    "largeDog": "大型犬OK",
    "fee": "無料",
    "hours": "終日",
    "access": "JR虹ノ松原駅から徒歩すぐ",
    "parking": "周辺に駐車場あり",
    "rainyOk": "屋外のため不可",
    "indoorOk": "周辺に飲食店あり",
    "dogAllowed": "リード必須",
    "officialUrl": "https://www.karatsu-kankou.jp/",
    "mapQuery": "虹の松原 唐津",
    "memo": "日本三大松原の一つ。松林の中を愛犬と散策できる絶好のコース。唐津城や唐津湾の景色も楽しめます。",
    "status": "公式要確認",
    "lastChecked": "2026-05-01",
    "weekendRecommended": True
  },
  {
    "id": "miyazaki-aoshima-beach-walk",
    "name": "青島ビーチ 犬連れ散歩",
    "area": "宮崎県宮崎市青島",
    "type": "walk",
    "large_dog": "大型犬OK・リード必須",
    "largeDog": "大型犬OK",
    "fee": "無料",
    "hours": "終日",
    "access": "JR青島駅から徒歩5分",
    "parking": "周辺に有料駐車場",
    "rainyOk": "屋外のため不可",
    "indoorOk": "周辺に飲食店あり",
    "dogAllowed": "リード必須（海水浴シーズン外）",
    "officialUrl": "https://www.kanko-miyazaki.jp/",
    "mapQuery": "青島ビーチ 宮崎",
    "memo": "鬼の洗濯板で有名な青島周辺のビーチ。シーズンオフは愛犬と砂浜を散歩できます。青島神社参道も犬連れで歩けます。",
    "status": "公式要確認",
    "lastChecked": "2026-05-01",
    "weekendRecommended": True
  },
  {
    "id": "kirishima-ebino-walk",
    "name": "えびの高原 散策コース",
    "area": "宮崎県えびの市",
    "type": "walk",
    "large_dog": "大型犬OK・リード必須",
    "largeDog": "大型犬OK",
    "fee": "無料（駐車場有料）",
    "hours": "終日（火山活動状況による）",
    "access": "宮崎自動車道えびのICから約30分",
    "parking": "えびの高原に駐車場あり",
    "rainyOk": "悪天候時は不可",
    "indoorOk": "売店・レストランあり",
    "dogAllowed": "リード必須",
    "officialUrl": "https://www.ebino-kogen.com/",
    "mapQuery": "えびの高原 散策",
    "memo": "霧島連山の中に広がる高原。池めぐりコースは約2時間で愛犬と一緒に楽しめます。秋は紅葉、冬は霧氷と四季折々の絶景が。",
    "status": "公式要確認",
    "lastChecked": "2026-05-01",
    "weekendRecommended": True
  },
  {
    "id": "kagoshima-sakurajima-walk",
    "name": "桜島 溶岩なぎさ公園",
    "area": "鹿児島県鹿児島市",
    "type": "walk",
    "large_dog": "大型犬OK・リード必須",
    "largeDog": "大型犬OK",
    "fee": "無料",
    "hours": "終日",
    "access": "桜島フェリー桟橋から車で5分",
    "parking": "公園内に無料駐車場",
    "rainyOk": "屋外のため不可",
    "indoorOk": "道の駅あり",
    "dogAllowed": "リード必須",
    "officialUrl": "https://www.sakurajima.gr.jp/",
    "mapQuery": "桜島 溶岩なぎさ公園",
    "memo": "桜島の溶岩が広がる独特の景観を愛犬と散策。足湯もあり（犬は入れません）。錦江湾越しに鹿児島市街を望む絶景スポット。",
    "status": "公式要確認",
    "lastChecked": "2026-05-01",
    "weekendRecommended": True
  },
  {
    "id": "ibusuki-sand-bath-area-walk",
    "name": "指宿 長崎鼻 散策",
    "area": "鹿児島県指宿市",
    "type": "walk",
    "large_dog": "大型犬OK・リード必須",
    "largeDog": "大型犬OK",
    "fee": "無料",
    "hours": "終日",
    "access": "JR山川駅からバスまたは車",
    "parking": "長崎鼻に無料駐車場",
    "rainyOk": "屋外のため不可",
    "indoorOk": "売店あり",
    "dogAllowed": "リード必須",
    "officialUrl": "https://www.ibusuki.or.jp/",
    "mapQuery": "指宿 長崎鼻",
    "memo": "薩摩半島の最南端。開聞岳を背景に広がる海岸線は絶景。愛犬と一緒に南国の雰囲気を満喫できます。",
    "status": "公式要確認",
    "lastChecked": "2026-05-01",
    "weekendRecommended": True
  },
  {
    "id": "takachiho-gorge-walk",
    "name": "高千穂峡 遊歩道散策",
    "area": "宮崎県西臼杵郡高千穂町",
    "type": "walk",
    "large_dog": "大型犬OK・リード必須",
    "largeDog": "大型犬OK",
    "fee": "無料（ボート乗船は別途）",
    "hours": "終日（遊歩道）",
    "access": "高千穂バスセンターから徒歩20分",
    "parking": "高千穂峡周辺に有料駐車場",
    "rainyOk": "屋外のため不可",
    "indoorOk": "周辺に飲食店あり",
    "dogAllowed": "リード必須（ボートは不可）",
    "officialUrl": "https://takachiho-kanko.info/",
    "mapQuery": "高千穂峡 遊歩道",
    "memo": "神話の里・高千穂の絶景渓谷。遊歩道は愛犬と一緒に歩けます（ボートは犬不可）。真名井の滝の迫力は圧巻。",
    "status": "公式要確認",
    "lastChecked": "2026-05-01",
    "weekendRecommended": True
  },
  {
    "id": "fukuoka-dogcafe-wan",
    "name": "ドッグカフェ WAN 福岡",
    "area": "福岡県福岡市",
    "type": "cafe",
    "large_dog": "大型犬OK（要確認）",
    "largeDog": "要確認",
    "fee": "飲食代のみ",
    "hours": "11:00〜20:00（不定休）",
    "access": "福岡市内（詳細は公式サイト参照）",
    "parking": "要確認",
    "rainyOk": "可（屋内）",
    "indoorOk": "可",
    "dogAllowed": "リード必須または抱っこ",
    "officialUrl": "https://www.google.com/search?q=ドッグカフェ+福岡",
    "mapQuery": "ドッグカフェ 福岡市",
    "memo": "愛犬と一緒にゆっくりできるカフェ。大型犬の場合は事前に確認が必要ですが、テラス席があるカフェは比較的大型犬OKが多いです。",
    "status": "公式要確認",
    "lastChecked": "2026-05-01",
    "weekendRecommended": True
  },
  {
    "id": "kumamoto-castle-walk",
    "name": "熊本城 二の丸公園",
    "area": "熊本県熊本市",
    "type": "walk",
    "large_dog": "大型犬OK・リード必須",
    "largeDog": "大型犬OK",
    "fee": "二の丸公園は無料（城内は有料）",
    "hours": "終日（公園部分）",
    "access": "熊本市電熊本城・市役所前電停から徒歩5分",
    "parking": "周辺に有料駐車場",
    "rainyOk": "屋外のため不可",
    "indoorOk": "周辺に飲食店あり",
    "dogAllowed": "リード必須・城内は犬不可",
    "officialUrl": "https://kumamoto-guide.jp/kumamoto-castle/",
    "mapQuery": "熊本城 二の丸公園",
    "memo": "熊本城を背景に愛犬と散歩できる二の丸公園。桜の季節は特に美しく、地元の人も多く訪れます。城内は犬不可なので注意。",
    "status": "公式要確認",
    "lastChecked": "2026-05-01",
    "weekendRecommended": True
  },
  {
    "id": "kumamoto-suizenji-walk",
    "name": "水前寺成趣園",
    "area": "熊本県熊本市",
    "type": "walk",
    "large_dog": "要確認",
    "largeDog": "要確認",
    "fee": "入園料：大人400円",
    "hours": "8:30〜17:00（季節変動あり）",
    "access": "熊本市電水前寺公園電停から徒歩3分",
    "parking": "周辺に有料駐車場",
    "rainyOk": "屋外のため不可",
    "indoorOk": "周辺に飲食店あり",
    "dogAllowed": "要確認",
    "officialUrl": "https://www.suizenji.or.jp/",
    "mapQuery": "水前寺成趣園 熊本",
    "memo": "東海道五十三次を模した庭園。湧水が美しく、熊本の自然の豊かさを感じられます。ペット可否は事前確認を。",
    "status": "公式要確認",
    "lastChecked": "2026-05-01",
    "weekendRecommended": False
  },
  {
    "id": "oita-beppu-umi-tamago",
    "name": "うみたまご（大分マリーンパレス水族館）周辺",
    "area": "大分県別府市",
    "type": "walk",
    "large_dog": "大型犬OK・リード必須（屋外エリア）",
    "largeDog": "大型犬OK（屋外のみ）",
    "fee": "施設入場は別途（屋外散策は無料）",
    "hours": "9:00〜17:00",
    "access": "別府市大字館浦字芝生 / 大分自動車道別府ICから約10分",
    "parking": "あり（有料）",
    "rainyOk": "屋外のため不可",
    "indoorOk": "水族館内は犬不可",
    "dogAllowed": "リード必須・施設内は不可",
    "officialUrl": "https://www.umitamago.jp/",
    "mapQuery": "うみたまご 別府 周辺",
    "memo": "別府湾沿いの水族館周辺の海岸散策。海を眺めながら愛犬と歩けます。水族館内は犬不可ですが、外の景色だけでも十分楽しめます。",
    "status": "公式要確認",
    "lastChecked": "2026-05-01",
    "weekendRecommended": True
  }
]

combined = existing + new_spots
print(f'合計: {len(combined)}件')

with open('spots.json', 'w', encoding='utf-8') as f:
    json.dump(combined, f, ensure_ascii=False, indent=2)
print('spots.json更新完了')
